# Generated by Django 4.0 on 2022-03-06 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kilos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('profile_for_unlike_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilos.userprofile')),
            ],
        ),
    ]
